# .github/workflows/bot.yml
name: BotDipus

on:
  schedule:
    # viernes 17:00 🇦🇷 (20:00 UTC)
    - cron: '0 20 * * 5'
  workflow_dispatch:      # para dispararlo manual

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - name: Create .env
        run: |
          echo "X_KEY=${{ secrets.X_KEY }}"         >> .env
          echo "X_SECRET=${{ secrets.X_SECRET }}"   >> .env
          echo "X_ACCESS_TOKEN=${{ secrets.X_ACCESS_TOKEN }}" >> .env
          echo "X_ACCESS_SECRET=${{ secrets.X_ACCESS_SECRET }}" >> .env

      - name: Actualizar datos
        run: bun run src/countFirmantes.ts

      - name: Publicar tweets
        run: bun run src/tweet.ts
